services:
  jenkins:
    build: ./jenkins
    privileged: true
    user: root
    ports:
      - "8888:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "7777:9000"
    container_name: sonarqube
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
